set(TARGET "$ENV{FUBI_T1PIDD_PATH}")
if(TARGET STREQUAL "")
    message(STATUS "t1pidd acceptance skipped: FUBI_T1PIDD_PATH is not set")
    return()
endif()
if(NOT EXISTS "${TARGET}")
    message(STATUS "t1pidd acceptance skipped: configured path does not exist")
    return()
endif()
if(NOT DEFINED FUBI OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "FUBI and OUTPUT_DIR are required")
endif()
file(SHA256 "${TARGET}" HASH)
if(NOT HASH STREQUAL "42b68a561b23fade1b62cfc35b361773b670a040f47214f085f8099101d41cdb")
    message(FATAL_ERROR "t1pidd identity mismatch: ${HASH}")
endif()
file(REMOVE "${OUTPUT_DIR}/t1pidd.loaded")
execute_process(COMMAND "${FUBI}" "${TARGET}" --list --json
    WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE RESULT
    OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "t1pidd catalog failed: ${RESULT}: ${ERROR}")
endif()
if(NOT OUTPUT MATCHES "\\\"name\\\":\\\"FxDriverEntryUm\\\"")
    message(FATAL_ERROR "expected t1pidd export was not found")
endif()
if(NOT OUTPUT MATCHES "\\\"rva\\\":32576")
    message(FATAL_ERROR "expected t1pidd export RVA was not found")
endif()
if(EXISTS "${OUTPUT_DIR}/t1pidd.loaded")
    message(FATAL_ERROR "static t1pidd catalog loaded the target")
endif()
execute_process(COMMAND "${FUBI}" "${TARGET}" --describe FxDriverEntryUm --json
    WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE DESCRIBE_RESULT
    OUTPUT_VARIABLE DESCRIBE_OUTPUT ERROR_VARIABLE DESCRIBE_ERROR)
if(NOT DESCRIBE_RESULT EQUAL 0 OR NOT DESCRIBE_OUTPUT MATCHES "framework-managed")
    message(FATAL_ERROR "t1pidd describe did not preserve framework-managed status: ${DESCRIBE_RESULT}: ${DESCRIBE_ERROR}")
endif()
if(EXISTS "${OUTPUT_DIR}/t1pidd.loaded")
    message(FATAL_ERROR "static t1pidd describe loaded the target")
endif()
message(STATUS "t1pidd acceptance passed for hash ${HASH}")
