if(NOT DEFINED FUBI OR NOT DEFINED FIXTURE OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "FUBI, FIXTURE, and OUTPUT_DIR are required")
endif()
if(NOT DEFINED ARCHITECTURE OR NOT ARCHITECTURE STREQUAL "x64")
    message(STATUS "Framework-managed call test skipped: controlled fixture profile is x64-only")
    return()
endif()
file(SHA256 "${FIXTURE}" HASH)
set(PROFILE "${OUTPUT_DIR}/framework-profile.json")
file(WRITE "${PROFILE}" "{\"schema_version\":1,\"module\":{\"sha256\":\"${HASH}\",\"architecture\":\"${ARCHITECTURE}\"},\"functions\":[{\"rva\":4288,\"selector\":\"FxDriverEntryUm\",\"abi\":\"${ARCHITECTURE}\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[],\"framework_managed\":true}]}")
file(REMOVE "${OUTPUT_DIR}/static_fixture.executed")
execute_process(COMMAND "${FUBI}" "${FIXTURE}" --call FxDriverEntryUm
    --profile "${PROFILE}" --json WORKING_DIRECTORY "${OUTPUT_DIR}"
    RESULT_VARIABLE ONE_RESULT OUTPUT_VARIABLE ONE_OUTPUT ERROR_VARIABLE ONE_ERROR)
if(NOT ONE_RESULT EQUAL 8)
    message(FATAL_ERROR "expected framework validation exit 8, got ${ONE_RESULT}: ${ONE_ERROR}")
endif()
string(FIND "${ONE_OUTPUT}" "framework-managed" ONE_DIAGNOSTIC)
if(ONE_DIAGNOSTIC LESS 0)
    message(FATAL_ERROR "framework call did not return stable diagnostic: ${ONE_OUTPUT}")
endif()
if(EXISTS "${OUTPUT_DIR}/static_fixture.executed")
    message(FATAL_ERROR "framework validation loaded the fixture")
endif()
file(WRITE "${OUTPUT_DIR}/framework-input.jsonl" "{\"schema_version\":1,\"action\":\"hello\",\"correlation_id\":\"hello\"}\n{\"schema_version\":1,\"action\":\"call\",\"correlation_id\":\"framework\",\"selector\":\"FxDriverEntryUm\",\"has_prototype_override\":true,\"prototype_override\":{\"abi\":\"x64\",\"quality\":\"user-declared\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[]}}\n{\"schema_version\":1,\"action\":\"quit\",\"correlation_id\":\"quit\"}\n")
execute_process(COMMAND powershell -NoProfile -NonInteractive -Command "$p=Start-Process -FilePath '${FUBI}' -ArgumentList @('${FIXTURE}','--profile','${PROFILE}','--jsonl') -RedirectStandardInput '${OUTPUT_DIR}/framework-input.jsonl' -RedirectStandardOutput '${OUTPUT_DIR}/framework-output.jsonl' -NoNewWindow -PassThru -Wait; exit $p.ExitCode" WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE SESSION_RESULT)
if(NOT SESSION_RESULT EQUAL 0)
    message(FATAL_ERROR "framework JSONL session failed: ${SESSION_RESULT}")
endif()
file(READ "${OUTPUT_DIR}/framework-output.jsonl" SESSION_OUTPUT)
string(FIND "${SESSION_OUTPUT}" "\"correlation_id\":\"framework\"" SESSION_CORRELATION)
string(FIND "${SESSION_OUTPUT}" "framework-managed" SESSION_DIAGNOSTIC)
if(SESSION_CORRELATION LESS 0 OR SESSION_DIAGNOSTIC LESS 0)
    message(FATAL_ERROR "framework JSONL dispatch was not rejected: ${SESSION_OUTPUT}")
endif()
if(EXISTS "${OUTPUT_DIR}/static_fixture.executed")
    message(FATAL_ERROR "framework JSONL validation loaded the fixture")
endif()
file(REMOVE "${PROFILE}" "${OUTPUT_DIR}/framework-input.jsonl" "${OUTPUT_DIR}/framework-output.jsonl")
