if(NOT DEFINED FUBI OR NOT DEFINED FIXTURE OR NOT DEFINED CONTROL_FIXTURE OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "FUBI, FIXTURE, CONTROL_FIXTURE, and OUTPUT_DIR are required")
endif()
if(NOT DEFINED ARCHITECTURE OR NOT ARCHITECTURE STREQUAL "x64")
    message(STATUS "Framework-managed call test skipped: controlled fixture profile is x64-only")
    return()
endif()
file(SHA256 "${FIXTURE}" HASH)
set(PROFILE "${OUTPUT_DIR}/framework-profile.json")
file(WRITE "${PROFILE}" "{\"schema_version\":1,\"module\":{\"sha256\":\"${HASH}\",\"architecture\":\"${ARCHITECTURE}\"},\"functions\":[{\"rva\":4288,\"selector\":\"FxDriverEntryUm\",\"abi\":\"${ARCHITECTURE}\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[],\"framework_managed\":true}]}")
file(REMOVE "${OUTPUT_DIR}/static_fixture.executed")
execute_process(COMMAND "${FUBI}" "${FIXTURE}" --call FxDriverEntryUm
    --profile "${PROFILE}" --json WORKING_DIRECTORY "${OUTPUT_DIR}"
    RESULT_VARIABLE ONE_RESULT OUTPUT_VARIABLE ONE_OUTPUT ERROR_VARIABLE ONE_ERROR)
if(NOT ONE_RESULT EQUAL 8)
    message(FATAL_ERROR "expected framework validation exit 8, got ${ONE_RESULT}: ${ONE_ERROR}")
endif()
string(FIND "${ONE_OUTPUT}" "framework-managed" ONE_DIAGNOSTIC)
string(FIND "${ONE_OUTPUT}" "\"status\":\"validation-failed\"" ONE_STATUS)
string(FIND "${ONE_OUTPUT}" "\"worker_exit_code\":null" ONE_WORKER)
if(ONE_DIAGNOSTIC LESS 0 OR ONE_STATUS LESS 0 OR ONE_WORKER LESS 0)
    message(FATAL_ERROR "framework call did not return stable diagnostic: ${ONE_OUTPUT}")
endif()
if(EXISTS "${OUTPUT_DIR}/static_fixture.executed")
    message(FATAL_ERROR "framework validation loaded the fixture")
endif()
file(WRITE "${OUTPUT_DIR}/framework-input.jsonl" "{\"schema_version\":1,\"action\":\"hello\",\"correlation_id\":\"hello\"}\n{\"schema_version\":1,\"action\":\"call\",\"correlation_id\":\"framework\",\"selector\":\"FxDriverEntryUm\",\"has_prototype_override\":true,\"prototype_override\":{\"abi\":\"x64\",\"quality\":\"user-declared\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[]}}\n{\"schema_version\":1,\"action\":\"quit\",\"correlation_id\":\"quit\"}\n")
set(SESSION_SCRIPT "${OUTPUT_DIR}/run-framework-jsonl.cmd")
file(WRITE "${SESSION_SCRIPT}"
    "@echo off\n"
    "\"%~1\" \"%~2\" --profile \"%~3\" --jsonl < \"%~4\"\n"
    "exit /b %ERRORLEVEL%\n")
execute_process(COMMAND cmd /c call "${SESSION_SCRIPT}" "${FUBI}" "${FIXTURE}" "${PROFILE}" "${OUTPUT_DIR}/framework-input.jsonl" OUTPUT_VARIABLE SESSION_OUTPUT ERROR_VARIABLE SESSION_ERROR RESULT_VARIABLE SESSION_RESULT)
if(NOT SESSION_RESULT EQUAL 0)
    message(FATAL_ERROR "framework JSONL session failed: ${SESSION_RESULT}: ${SESSION_ERROR}")
endif()
string(REPLACE "\r\n" "\n" SESSION_NORMALIZED "${SESSION_OUTPUT}")
string(REPLACE "\n" ";" SESSION_LINES "${SESSION_NORMALIZED}")
set(SESSION_COUNT 0)
foreach(line IN LISTS SESSION_LINES)
    if(NOT line STREQUAL "")
        math(EXPR SESSION_COUNT "${SESSION_COUNT} + 1")
    endif()
endforeach()
if(NOT SESSION_COUNT EQUAL 3)
    message(FATAL_ERROR "expected exactly three JSONL response lines: ${SESSION_OUTPUT}")
endif()
string(FIND "${SESSION_OUTPUT}" "\"correlation_id\":\"framework\"" SESSION_CORRELATION)
string(FIND "${SESSION_OUTPUT}" "framework-managed" SESSION_DIAGNOSTIC)
string(FIND "${SESSION_OUTPUT}" "\"status\":\"validation-failed\"" SESSION_STATUS)
if(SESSION_CORRELATION LESS 0 OR SESSION_DIAGNOSTIC LESS 0 OR SESSION_STATUS LESS 0)
    message(FATAL_ERROR "framework JSONL dispatch was not rejected: ${SESSION_OUTPUT}")
endif()
if(EXISTS "${OUTPUT_DIR}/static_fixture.executed")
    message(FATAL_ERROR "framework JSONL validation loaded the fixture")
endif()
file(REMOVE "${OUTPUT_DIR}/export_fixture.executed")
file(SHA256 "${CONTROL_FIXTURE}" CONTROL_HASH)
set(NORMAL_PROFILE "${OUTPUT_DIR}/framework-normal-profile.json")
file(WRITE "${NORMAL_PROFILE}" "{\"schema_version\":1,\"module\":{\"sha256\":\"${CONTROL_HASH}\",\"architecture\":\"${ARCHITECTURE}\"},\"functions\":[{\"rva\":4096,\"selector\":\"NamedExport\",\"abi\":\"${ARCHITECTURE}\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[]}]}")
execute_process(COMMAND "${FUBI}" "${CONTROL_FIXTURE}" --call NamedExport --prototype-override "${NORMAL_PROFILE}" --json WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE NORMAL_RESULT OUTPUT_VARIABLE NORMAL_OUTPUT ERROR_VARIABLE NORMAL_ERROR)
if(NOT NORMAL_RESULT EQUAL 0)
    message(FATAL_ERROR "non-framework control failed: ${NORMAL_RESULT}: ${NORMAL_ERROR}")
endif()
string(FIND "${NORMAL_OUTPUT}" "\"schema_version\":1" NORMAL_SUCCESS)
if(NORMAL_SUCCESS LESS 0 OR NOT EXISTS "${OUTPUT_DIR}/export_fixture.executed")
    message(FATAL_ERROR "non-framework static control did not succeed safely: ${NORMAL_OUTPUT}")
endif()
file(REMOVE "${PROFILE}" "${NORMAL_PROFILE}" "${SESSION_SCRIPT}" "${OUTPUT_DIR}/framework-input.jsonl" "${OUTPUT_DIR}/static_fixture.executed" "${OUTPUT_DIR}/export_fixture.executed")
