if(NOT ARCHITECTURE STREQUAL "x86")
    return()
endif()
execute_process(COMMAND "${FUBI}" "${FIXTURE}" --list --json RESULT_VARIABLE rc OUTPUT_VARIABLE catalog)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "x86 fixture catalog failed")
endif()
file(SHA256 "${FIXTURE}" hash)
set(profile "${OUTPUT_DIR}/x86-worker-profile.json")
set(rvas "")
foreach(name CdeclZero CdeclAdd StdcallAdd CdeclFour CdeclEight)
    string(REGEX MATCH "\\\"rva\\\":([0-9]+),\\\"end_rva\\\"[^}]*\\\"name\\\":\\\"${name}\\\"" match "${catalog}")
    if(NOT match)
        message(FATAL_ERROR "missing ${name}")
    endif()
    list(APPEND rvas "${CMAKE_MATCH_1}")
endforeach()
list(GET rvas 0 r0)
list(GET rvas 1 r1)
list(GET rvas 2 r2)
list(GET rvas 3 r3)
list(GET rvas 4 r4)
file(WRITE "${profile}" "{\"schema_version\":1,\"module\":{\"sha256\":\"${hash}\",\"architecture\":\"x86\"},\"functions\":[{\"rva\":${r0},\"selector\":\"CdeclZero\",\"abi\":\"__cdecl\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[]},{\"rva\":${r1},\"selector\":\"CdeclAdd\",\"abi\":\"__cdecl\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32}]},{\"rva\":${r2},\"selector\":\"StdcallAdd\",\"abi\":\"__stdcall\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32}]},{\"rva\":${r3},\"selector\":\"CdeclFour\",\"abi\":\"__cdecl\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32}]},{\"rva\":${r4},\"selector\":\"CdeclEight\",\"abi\":\"__cdecl\",\"return_type\":{\"kind\":\"integer\",\"width\":32},\"parameters\":[{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32},{\"kind\":\"integer\",\"width\":32}]}]}")
function(run expected)
    execute_process(COMMAND "${FUBI}" "${FIXTURE}" ${ARGN} --profile "${profile}" --json RESULT_VARIABLE call_rc OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT call_rc EQUAL 0 OR NOT output MATCHES "\\\"return_value\\\":\\\"${expected}\\\"")
        message(FATAL_ERROR "x86 call failed: ${call_rc} ${error} ${output}")
    endif()
endfunction()
run(17 --call CdeclZero)
run(12 --call CdeclAdd --arg integer:7 --arg integer:5)
run(13 --call "#3" --arg integer:9 --arg integer:4)
run(1234 --call CdeclFour --arg integer:1 --arg integer:2 --arg integer:3 --arg integer:4)
run(36 --call CdeclEight --arg integer:1 --arg integer:2 --arg integer:3 --arg integer:4 --arg integer:5 --arg integer:6 --arg integer:7 --arg integer:8)
file(READ "${profile}" valid_profile)
string(REPLACE "\"architecture\":\"x86\"" "\"architecture\":\"x64\"" invalid_profile "${valid_profile}")
set(invalid_path "${OUTPUT_DIR}/x86-invalid-profile.json")
file(WRITE "${invalid_path}" "${invalid_profile}")
execute_process(COMMAND "${FUBI}" "${FIXTURE}" --call CdeclAdd --arg integer:1 --arg integer:2 --profile "${invalid_path}" --json RESULT_VARIABLE mismatch_rc)
if(NOT mismatch_rc EQUAL 6)
    message(FATAL_ERROR "x64 ABI/profile was not rejected before loading: ${mismatch_rc}")
endif()
file(REMOVE "${profile}" "${invalid_path}")
