if(NOT DEFINED ACCEPTANCE_FILE OR "${ACCEPTANCE_FILE}" STREQUAL "")
    message(STATUS "Acceptance skipped: FUBI_ACCEPTANCE_BINARY was not supplied")
    return()
endif()
if(NOT EXISTS "${ACCEPTANCE_FILE}")
    message(STATUS "Acceptance skipped: supplied binary is unavailable: ${ACCEPTANCE_FILE}")
    return()
endif()
if(NOT DEFINED SHA256 OR SHA256 STREQUAL "")
    message(STATUS "Acceptance skipped: no SHA-256 pin was supplied")
    return()
endif()
file(SHA256 "${ACCEPTANCE_FILE}" actual_sha256)
if(NOT actual_sha256 STREQUAL SHA256)
    message(FATAL_ERROR "Acceptance refused: supplied binary SHA-256 does not match the pin")
endif()
execute_process(COMMAND "${FUBI}" "${ACCEPTANCE_FILE}" --list --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Acceptance static catalog failed (${result}): ${diagnostics}")
endif()
if(output STREQUAL "")
    message(FATAL_ERROR "Acceptance static catalog produced no JSON output")
endif()
message(STATUS "Acceptance static catalog passed for supplied binary")
