# Opt-in static acceptance for a locally supplied T1PIDD image.
set(target "$ENV{FUBI_T1PIDD_PATH}")
if(target STREQUAL "")
    message(STATUS "T1PIDD acceptance skipped: FUBI_T1PIDD_PATH is not set")
    return()
endif()
if(NOT EXISTS "${target}")
    message(STATUS "T1PIDD acceptance skipped: supplied image is unavailable: ${target}")
    return()
endif()
if(NOT DEFINED FUBI OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "FUBI and OUTPUT_DIR are required")
endif()

file(SHA256 "${target}" actual_sha256)
set(expected_sha256 "42b68a561b23fade1b62cfc35b361773b670a040f47214f085f8099101d41cdb")
if(NOT actual_sha256 STREQUAL expected_sha256)
    message(STATUS "T1PIDD acceptance skipped: SHA-256 does not match the expected reference module")
    return()
endif()
set(marker "${OUTPUT_DIR}/t1pidd.loaded")
if(DEFINED ENV{FUBI_T1PIDD_MARKER} AND NOT "$ENV{FUBI_T1PIDD_MARKER}" STREQUAL "")
    set(marker "$ENV{FUBI_T1PIDD_MARKER}")
endif()
file(REMOVE "${marker}")

execute_process(COMMAND "${FUBI}" "${target}" --list --json
    RESULT_VARIABLE list_result OUTPUT_VARIABLE list_output ERROR_VARIABLE list_error)
if(NOT list_result EQUAL 0)
    message(FATAL_ERROR "T1PIDD static list failed (${list_result}): ${list_error}")
endif()
if(NOT list_output MATCHES "\\\"sha256\\\":\\\"${actual_sha256}\\\"")
    message(FATAL_ERROR "T1PIDD catalog did not report the input SHA-256")
endif()
if(NOT list_output MATCHES "\\\"architecture\\\":\\\"(x86|x64)\\\"")
    message(FATAL_ERROR "T1PIDD catalog did not report a supported architecture")
endif()
set(target_architecture "${CMAKE_MATCH_1}")
if(NOT list_output MATCHES "\\\"functions\\\":\\[")
    message(FATAL_ERROR "T1PIDD catalog did not report function candidates")
endif()
if(NOT list_output MATCHES "\\\"name\\\":\\\"FxDriverEntryUm\\\"")
    message(FATAL_ERROR "T1PIDD catalog did not preserve FxDriverEntryUm")
endif()
if(NOT list_output MATCHES "\\\"rva\\\":32576")
    message(FATAL_ERROR "T1PIDD catalog did not preserve FxDriverEntryUm RVA 0x7F40")
endif()
if(NOT list_output MATCHES "\\\"name\\\":\\\"OpenTriggerDevice\\\"")
    message(FATAL_ERROR "T1PIDD catalog did not preserve OpenTriggerDevice")
endif()
if(DEFINED ENV{FUBI_T1PIDD_VERSION} AND NOT "$ENV{FUBI_T1PIDD_VERSION}" STREQUAL "")
    if(NOT list_output MATCHES "$ENV{FUBI_T1PIDD_VERSION}")
        message(FATAL_ERROR "T1PIDD version metadata does not match FUBI_T1PIDD_VERSION")
    endif()
endif()
string(REGEX MATCHALL "\\\"rva\\\":[0-9]+" candidate_matches "${list_output}")
list(LENGTH candidate_matches candidate_count)
if(NOT candidate_count EQUAL 149)
    message(FATAL_ERROR "T1PIDD candidate count mismatch: ${candidate_count}, expected 149")
endif()
string(REGEX MATCHALL "exception-directory" exception_matches "${list_output}")
string(REGEX MATCHALL "guard-cf" guard_matches "${list_output}")
string(REGEX MATCHALL "pe-export" export_matches "${list_output}")
list(LENGTH exception_matches exception_count)
list(LENGTH guard_matches guard_count)
list(LENGTH export_matches export_count)
if(NOT exception_count EQUAL 146 OR NOT guard_count EQUAL 2 OR NOT export_count EQUAL 1)
    message(FATAL_ERROR "T1PIDD provenance counts mismatch: exception=${exception_count}, guard=${guard_count}, export=${export_count}")
endif()
if(NOT list_output MATCHES "\\\"address_sources\\\":\\[[^]]+\\]")
    message(FATAL_ERROR "T1PIDD catalog did not preserve candidate address evidence")
endif()

string(REGEX MATCH "\\\"rva\\\":([0-9]+)" first_match "${list_output}")
if(NOT first_match)
    message(FATAL_ERROR "T1PIDD catalog did not expose a candidate RVA")
endif()
set(first_rva "${CMAKE_MATCH_1}")
math(EXPR first_rva_hex "${first_rva}" OUTPUT_FORMAT HEXADECIMAL)
execute_process(COMMAND "${FUBI}" "${target}" --describe "${first_rva_hex}" --json
    RESULT_VARIABLE describe_result OUTPUT_VARIABLE describe_output ERROR_VARIABLE describe_error)
if(NOT describe_result EQUAL 0 OR NOT describe_output MATCHES "\\\"schema_version\\\":1")
    message(FATAL_ERROR "T1PIDD static describe failed (${describe_result}): ${describe_error}")
endif()
execute_process(COMMAND "${FUBI}" "${target}" --describe FxDriverEntryUm --json
    RESULT_VARIABLE inspect_result OUTPUT_VARIABLE inspect_output ERROR_VARIABLE inspect_error)
if(NOT inspect_result EQUAL 0 OR NOT inspect_output MATCHES "framework-managed|requires-prototype")
    message(FATAL_ERROR "T1PIDD description did not preserve non-callable uncertainty: ${inspect_error}")
endif()

set(profile "${OUTPUT_DIR}/t1pidd_profile_skeleton.json")
file(WRITE "${profile}" "{\"schema_version\":1,\"module\":{\"sha256\":\"${actual_sha256}\",\"architecture\":\"${target_architecture}\"},\"functions\":[]}\n")
execute_process(COMMAND "${FUBI}" "${target}" --list --json --profile "${profile}"
    RESULT_VARIABLE profile_result OUTPUT_VARIABLE profile_output ERROR_VARIABLE profile_error)
file(REMOVE "${profile}")
if(NOT profile_result EQUAL 0)
    message(FATAL_ERROR "T1PIDD prototype skeleton failed (${profile_result}): ${profile_error}")
endif()
set(marker "${OUTPUT_DIR}/t1pidd.loaded")
if(DEFINED ENV{FUBI_T1PIDD_MARKER} AND NOT "$ENV{FUBI_T1PIDD_MARKER}" STREQUAL "")
    set(marker "$ENV{FUBI_T1PIDD_MARKER}")
endif()
if(EXISTS "${marker}")
        message(FATAL_ERROR "T1PIDD static acceptance observed a load marker")
endif()
message(STATUS "T1PIDD static acceptance passed: hash, architecture, candidates, describe, and prototype skeleton")
